apiVersion: v1
kind: Secret

metadata:
  name: database-secret

type: Opaque

stringData:
  POSTGRES_DB: hireflow
  POSTGRES_USER: hireflow
  POSTGRES_PASSWORD: hireflow_password
  DATABASE_URL: postgresql://hireflow:hireflow_password@database-service:5432/hireflow
  JWT_SECRET: "XUAt+mhuXi+NVXZVCNT2zPne4CNzo8IEWEF01Eg2FqAu120DGqi0CtyBTIz8e3iLW8zw5eDXNxsXp/8GHdgTOg=="